# Generated by Django 3.1.3 on 2020-11-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emaim',
            new_name='email',
        ),
    ]
